# CodeRabbit AI Review Policy for Project Chimera
# Purpose: Enforce spec alignment, security, and test discipline
# Schema: https://coderabbit.ai/integrations/schema.v2.json

language: "en-US"
tone_instructions: >
  Enforce alignment with specs/ (authoritative). Flag code not referenced in specs,
  missing tests for new behavior, hardcoded secrets, direct external API calls,
  and bypass of MCP or governance layers. Conservative, strict tone.

reviews:
  profile: assertive
  request_changes_workflow: true
  high_level_summary: true
  path_instructions:
    - path: "specs/**"
      instructions: "Treat specs/ as authoritative; flag changes that contradict or bypass them."
    - path: "**/*.py"
      instructions: "Flag missing tests for new behavior; no hardcoded secrets or unvalidated external input."
  pre_merge_checks:
    description:
      mode: warning
    title:
      mode: warning
